const GRADIENT_LEN = 7,
  NUM_ACCENT_GRADIENTS = 4,
  NUM_NEUTRAL_GRADIENTS = 1,
  NUM_PRIMARY_GRADIENTS = 1;
export {
  GRADIENT_LEN,
  NUM_ACCENT_GRADIENTS,
  NUM_NEUTRAL_GRADIENTS,
  NUM_PRIMARY_GRADIENTS
};
