const COLOR_GRID_UPDATED = 'COLOR_GRID_UPDATED';
const OVERRIDE_SELECTED_COLOR = 'OVERRIDE_SELECTED_COLOR';
const RESET_SELECTED_COLOR = 'RESET_SELECTED_COLOR';
const UPDATE_SELECTED_COLOR = 'UPDATE_SELECTED_COLOR';

export {
  COLOR_GRID_UPDATED,
  RESET_SELECTED_COLOR,
  OVERRIDE_SELECTED_COLOR,
  UPDATE_SELECTED_COLOR
};
